### ISSUE TITLE
still dont working, is there any conflicts?

### ISSUE THREAD

**Issue by VoodoomanRUS** [MengLeiFudge/MLJ_DSPmods#1]
HI i've got
bepinex 5.4.22
ldbtool 3.0.1
CommonAPI 1.6.5 and
DSPmodsave 1.2.1
these all starting and functioning correctly
but with any config i cant see any fractionator recipes

[LogOutput.log](https://github.com/MengLeiFudge/MLJ_DSPmods/files/14469087/LogOutput.log)

![Снимок экрана 2024-03-02 180410](https://github.com/MengLeiFudge/MLJ_DSPmods/assets/79595645/673f90a4-2d4a-4b8f-a9a9-5c7d7def1d0a)

can u help how to solve this or solve this by urself?

btw i checked my helmod and i noticed that i can see your mod recipes but i cant do this inside the Replicator interface
![Снимок экрана 2024-03-02 182243](https://github.com/MengLeiFudge/MLJ_DSPmods/assets/79595645/1682cc81-f99b-4ebc-998b-f0f0440537d8)

**Comment by MengLeiFudge** [comment]
I apologize for taking so long to reply to you in the past.
First of all, to answer your question: even if you don't see the added fractionation recipes, you can still use the fractionation tower to fractionate them.
The fact is that this mod is a half-baked one (especially version 1.0.x) and it still has some content that needs to be updated. When I first made this mod, I focused on the implementation of the fractionation feature and didn't code the display side.
Some time ago I saw your feedback and then I started updating the mod by adding a lot of features to it, which included explicitly displaying all the added fractionation recipes on the crafting page.
Now I've pushed version 1.1.0 of the mod and you can download it.
The next update planned is: replacing the icons for all recipes with a fractionation style version (similar to what is done for deuterium  fractionation) instead of the current straight product icons.
Finally, thanks again for your feedback!
