### ISSUE TITLE
Deuterium fractionation

### ISSUE THREAD

**Issue by Largo2208** [MengLeiFudge/MLJ_DSPmods#10]
I can't seem to be able to fractionate:
1- Blue to Red Matrices
2- Red to Yellow Matrices
3- Hydrogen to Deuterium

**Comment by MengLeiFudge** [comment]
1/2. please check “Settings - Miscellaneous” in the game and toggle “Enable Matrix Fractionation” so that you can fractionate the matrix and can see them in manual making window.
3. Only the vanilla fractionator can fractionate hydrogen into deuterium. Also, the natural resource fractionator can fractionate hydrogen to hydrogen or deuterium to deuterium.

**Comment by MengLeiFudge** [comment]
v1.4.3 fixed the bug that Hydrogen can not fractionate to Deuterium when use origin fractionator.
