### ISSUE TITLE
Can't see the new recipes for almost all fabricator-produced items

### ISSUE THREAD

**Issue by uepoch** [MengLeiFudge/MLJ_DSPmods#11]
Hello,

I'm not sure if there's a conflicting mod that may create this, but I can't seem to have any fracturing recipe available for all fabricated items.

The techs also don't show any new recipes being unlocked, besides ore processing

![image](https://github.com/user-attachments/assets/1092c2e9-36bf-4286-b0a9-e3fe1bfee855)
![image](https://github.com/user-attachments/assets/c3c7676c-111c-4b4f-a377-0d2735c00921)

Any idea or pointer ? I see that a lot have changed in 1.4.1

**Comment by MengLeiFudge** [comment]
This is intentional. I removed a large number of recipes in v1.4.3 because they would have massively reduced the use of the game's original buildings, which made for a diminished gameplay experience. See here for specific information:
https://github.com/MengLeiFudge/MLJ_DSPmods/blob/6563aed286c057e0f4193357f97a12d8c41b5423/FractionateEverything/src/Main/Translation.cs#L35

**Comment by MengLeiFudge** [comment]
Of course, you don't have to worry about these recipes. In the next major release, you can get some of the fractionation recipes by drawing cards (maybe like Genshin Impact). Stay tuned for the next release!
