### ISSUE TITLE
FractionateEverything 1.3

### ISSUE THREAD

**Issue by iGeMiNix** [MengLeiFudge/MLJ_DSPmods#5]
Hello, love your mod. It looks like the new update might have a bug in the English version as it is making the raw materials on the planet into Chinese while the rest of the HUD stays in English. This can be easily replicated as the issue goes away when the mod is disable and comes back when the the mod is enabled. A fix would be appreciated. Thanks,

**Comment by MengLeiFudge** [comment]
First of all, thank you for using this mod! I appreciate your feedback and I will try to fix it later. For now I have also found other issues that existed in v1.3.0 and they will be fixed along with the 1.3.1 release. I'd also appreciate any other suggestions for feedback.

**Comment by MengLeiFudge** [comment]
The reason is that I executed `LDB.veins.OnAfterDeserialize();`, which modifies the name of the veins.
https://github.com/MengLeiFudge/MLJ_DSPmods/blob/d5712c9698e0151f5a2a5236b3413a98332690a6/FractionateEverything/src/FractionateEverything.cs#L185
Fixed it. I'll be pushing v1.3.1 to R2 in a couple hours.
